name: Miroslav Csonka
markdown: kramdown
layout: home
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
locale: "en-US"
title: "Miroslav Csonka's blog"
title_separator: "-"
author_profile: true
search: true
plugins:
  - jekyll-include-cache
  - jekyll-feed

author:
  name: "Miroslav Csonka"
  avatar: "/assets/avatar.png"
  location: "London, UK"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/miroslav-csonka-68973671"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MiroslavCsonka"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/miroslavcsonka"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      toc: true
      comments: true
      share: true
      related: true
      show_date: true

analytics:
  provider: "custom"
  google:
    tracking_id: "UA-1234567-8"
    anonymize_ip: false # default
