name: Miroslav Csonka
markdown: kramdown
layout: home
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
locale: "en-US"
title: "Miro's blog"
title_separator: "-"
author_profile: true
plugins:
  - jekyll-include-cache

author:
  name: "Miroslav Csonka"
  avatar: "/assets/avatar.png"
  location: "London, UK"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/miroslav-csonka-68973671"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MiroslavCsonka"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

